export function generateMarkdownExport(analysis: any, documentNames: string[] = []): string {
  const result = analysis.resultJson || {};
  const clauses = result.clauses || [];
  const obligations = result.obligations || [];
  const checklist = result.checklist || [];

  return `
# Clarifex Legal Assessment Report

**Analysis ID:** ${analysis.id}  
**Date:** ${new Date(analysis.createdAt || Date.now()).toLocaleDateString()}  
**Target Documents:** ${documentNames.join(", ") || "Contract Document"}  
**Risk Score:** ${analysis.riskScore || result.riskScore || "N/A"} / 10.0  
**AI Model:** ${analysis.modelUsed}  
**Comprehension Level:** ${analysis.comprehensionLevel}  

---

## 1. Executive Summary
${result.summary || "No summary available."}

${
  result.comprehensionLevelContent
    ? `\n### Level Breakdown (${analysis.comprehensionLevel})\n${result.comprehensionLevelContent}\n`
    : ""
}

---

## 2. Risk Heat-Map & Critical Clauses

${
  clauses.length === 0
    ? "No flagged clauses."
    : clauses
        .map(
          (c: any, i: number) => `
### ${i + 1}. [${c.riskLevel.toUpperCase()}] ${c.title || "Clause"} (Page ${c.pageRef || 1})
> "${c.text}"

**Risk Analysis:** ${c.reason}  
**Clause Fingerprint:** \`${c.fingerprint || "N/A"}\`
`,
        )
        .join("\n")
}

---

## 3. Obligations & Critical Dates Timeline

${
  obligations.length === 0
    ? "No specific dates or obligations extracted."
    : obligations
        .map(
          (o: any) =>
            `- **${o.dueDate || "Milestone"}:** ${o.description} *(Parties: ${(o.parties || []).join(", ") || "All"})*`,
        )
        .join("\n")
}

---

## 4. Execution Checklist

${
  checklist.length === 0
    ? "No checklist items generated."
    : checklist
        .map(
          (item: any) =>
            `- [ ] **[${item.importance?.toUpperCase() || "TODO"}] ${item.label}**  \n  *Why:* ${item.explanation}`,
        )
        .join("\n")
}

---

*Disclaimer: This report was generated by Clarifex AI Assistant for informational purposes and does not constitute formal legal counsel. Always consult a qualified attorney for legal representation.*
`.trim();
}
