import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { renderPdfToBuffer } from "@/lib/export/pdf";
import { sendAnalysisViaGmail } from "@/lib/google/gmail";

export async function POST(req: NextRequest) {
  const session = await auth();
  if (!session?.user?.id || !session.user.email) {
    return NextResponse.json({ error: "Unauthorized or missing email" }, { status: 401 });
  }

  try {
    const { analysisId } = await req.json();
    if (!analysisId) {
      return NextResponse.json({ error: "analysisId is required" }, { status: 400 });
    }

    const analysis = await prisma.analysis.findFirst({
      where: { id: analysisId, userId: session.user.id },
    });

    if (!analysis) {
      return NextResponse.json({ error: "Analysis not found" }, { status: 404 });
    }

    const docs = await prisma.document.findMany({
      where: { id: { in: analysis.documentIds } },
      select: { name: true },
    });

    const pdfBuffer = await renderPdfToBuffer(
      analysis,
      docs.map((d) => d.name),
    );

    const accessToken = (session as any).accessToken;

    if (!accessToken) {
      // In dev without Gmail token, return informative status
      return NextResponse.json({
        success: true,
        message: "Simulation: OAuth Gmail token required in production",
      });
    }

    const gmailRes = await sendAnalysisViaGmail({
      accessToken,
      to: session.user.email,
      subject: `[Clarifex] Legal Analysis Report #${analysis.id.slice(-6)}`,
      bodyText: `Hello,\n\nPlease find attached your comprehensive legal assessment report generated by Clarifex Legal AI.\n\nRisk Score: ${analysis.riskScore || "N/A"}/10\nModel Used: ${analysis.modelUsed}\n\nBest regards,\nClarifex Legal Assistant`,
      pdfAttachmentBase64: pdfBuffer.toString("base64"),
      pdfFileName: `Clarifex_Analysis_${analysis.id.slice(-6)}.pdf`,
    });

    return NextResponse.json(gmailRes);
  } catch (error) {
    console.error("Gmail export error:", error);
    return NextResponse.json(
      { error: (error as Error).message || "Failed to send Gmail" },
      { status: 500 },
    );
  }
}
