import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
    DATABASE_URL: z.string().url().default("postgresql://user:password@localhost:5432/clarifex?sslmode=disable"),
    NEXTAUTH_URL: z.string().url().default("http://localhost:3000"),
    NEXTAUTH_SECRET: z.string().min(1).default("dev-secret-key-32-characters-minimum-for-clarifex"),

    GOOGLE_CLIENT_ID: z.string().default(""),
    GOOGLE_CLIENT_SECRET: z.string().default(""),

    GITHUB_CLIENT_ID: z.string().default(""),
    GITHUB_CLIENT_SECRET: z.string().default(""),

    RECAPTCHA_SECRET_KEY: z.string().default(""),
    GOOGLE_CLOUD_API_KEY: z.string().default(""),
    GOOGLE_TRANSLATE_API_KEY: z.string().default(""),
    GOOGLE_SAFE_BROWSING_API_KEY: z.string().default(""),

    GOOGLE_CALENDAR_CLIENT_ID: z.string().default(""),
    GOOGLE_CALENDAR_CLIENT_SECRET: z.string().default(""),
    GOOGLE_DRIVE_API_KEY: z.string().default(""),

    FIREBASE_ADMIN_PRIVATE_KEY: z.string().default(""),
    FIREBASE_ADMIN_CLIENT_EMAIL: z.string().default(""),

    OPENROUTER_API_KEY: z.string().default(""),

    CLOUDFLARE_R2_ACCOUNT_ID: z.string().default(""),
    CLOUDFLARE_R2_ACCESS_KEY_ID: z.string().default(""),
    CLOUDFLARE_R2_SECRET_ACCESS_KEY: z.string().default(""),
    CLOUDFLARE_R2_BUCKET_NAME: z.string().default("clarifex-documents"),

    UPSTASH_REDIS_REST_URL: z.string().default(""),
    UPSTASH_REDIS_REST_TOKEN: z.string().default(""),

    ALGOLIA_ADMIN_KEY: z.string().default(""),

    RESEND_API_KEY: z.string().default(""),
    RESEND_FROM_EMAIL: z.string().default("noreply@clarifex.app"),

    SENTRY_AUTH_TOKEN: z.string().default(""),
    SENTRY_ORG: z.string().default(""),
    SENTRY_PROJECT: z.string().default(""),
  },
  client: {
    NEXT_PUBLIC_APP_URL: z.string().default("http://localhost:3000"),
    NEXT_PUBLIC_RECAPTCHA_SITE_KEY: z.string().default(""),
    NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: z.string().default(""),
    NEXT_PUBLIC_GOOGLE_DRIVE_CLIENT_ID: z.string().default(""),
    NEXT_PUBLIC_GA_MEASUREMENT_ID: z.string().default(""),
    NEXT_PUBLIC_GTM_ID: z.string().default(""),
    NEXT_PUBLIC_FIREBASE_API_KEY: z.string().default(""),
    NEXT_PUBLIC_FIREBASE_PROJECT_ID: z.string().default(""),
    NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: z.string().default(""),
    NEXT_PUBLIC_FIREBASE_APP_ID: z.string().default(""),
    NEXT_PUBLIC_R2_PUBLIC_URL: z.string().default(""),
    NEXT_PUBLIC_ALGOLIA_APP_ID: z.string().default(""),
    NEXT_PUBLIC_ALGOLIA_SEARCH_KEY: z.string().default(""),
    NEXT_PUBLIC_SENTRY_DSN: z.string().default(""),
  },
  runtimeEnv: {
    NODE_ENV: process.env.NODE_ENV,
    DATABASE_URL: process.env.DATABASE_URL,
    NEXTAUTH_URL: process.env.NEXTAUTH_URL,
    NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID,
    GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET,
    RECAPTCHA_SECRET_KEY: process.env.RECAPTCHA_SECRET_KEY,
    GOOGLE_CLOUD_API_KEY: process.env.GOOGLE_CLOUD_API_KEY,
    GOOGLE_TRANSLATE_API_KEY: process.env.GOOGLE_TRANSLATE_API_KEY,
    GOOGLE_SAFE_BROWSING_API_KEY: process.env.GOOGLE_SAFE_BROWSING_API_KEY,
    GOOGLE_CALENDAR_CLIENT_ID: process.env.GOOGLE_CALENDAR_CLIENT_ID,
    GOOGLE_CALENDAR_CLIENT_SECRET: process.env.GOOGLE_CALENDAR_CLIENT_SECRET,
    GOOGLE_DRIVE_API_KEY: process.env.GOOGLE_DRIVE_API_KEY,
    FIREBASE_ADMIN_PRIVATE_KEY: process.env.FIREBASE_ADMIN_PRIVATE_KEY,
    FIREBASE_ADMIN_CLIENT_EMAIL: process.env.FIREBASE_ADMIN_CLIENT_EMAIL,
    OPENROUTER_API_KEY: process.env.OPENROUTER_API_KEY,
    CLOUDFLARE_R2_ACCOUNT_ID: process.env.CLOUDFLARE_R2_ACCOUNT_ID,
    CLOUDFLARE_R2_ACCESS_KEY_ID: process.env.CLOUDFLARE_R2_ACCESS_KEY_ID,
    CLOUDFLARE_R2_SECRET_ACCESS_KEY: process.env.CLOUDFLARE_R2_SECRET_ACCESS_KEY,
    CLOUDFLARE_R2_BUCKET_NAME: process.env.CLOUDFLARE_R2_BUCKET_NAME,
    UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL,
    UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN,
    ALGOLIA_ADMIN_KEY: process.env.ALGOLIA_ADMIN_KEY,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    RESEND_FROM_EMAIL: process.env.RESEND_FROM_EMAIL,
    SENTRY_AUTH_TOKEN: process.env.SENTRY_AUTH_TOKEN,
    SENTRY_ORG: process.env.SENTRY_ORG,
    SENTRY_PROJECT: process.env.SENTRY_PROJECT,

    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_RECAPTCHA_SITE_KEY: process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY,
    NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY,
    NEXT_PUBLIC_GOOGLE_DRIVE_CLIENT_ID: process.env.NEXT_PUBLIC_GOOGLE_DRIVE_CLIENT_ID,
    NEXT_PUBLIC_GA_MEASUREMENT_ID: process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID,
    NEXT_PUBLIC_GTM_ID: process.env.NEXT_PUBLIC_GTM_ID,
    NEXT_PUBLIC_FIREBASE_API_KEY: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
    NEXT_PUBLIC_FIREBASE_PROJECT_ID: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    NEXT_PUBLIC_FIREBASE_APP_ID: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
    NEXT_PUBLIC_R2_PUBLIC_URL: process.env.NEXT_PUBLIC_R2_PUBLIC_URL,
    NEXT_PUBLIC_ALGOLIA_APP_ID: process.env.NEXT_PUBLIC_ALGOLIA_APP_ID,
    NEXT_PUBLIC_ALGOLIA_SEARCH_KEY: process.env.NEXT_PUBLIC_ALGOLIA_SEARCH_KEY,
    NEXT_PUBLIC_SENTRY_DSN: process.env.NEXT_PUBLIC_SENTRY_DSN,
  },
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
});
